### ISSUE TITLE
Required if validator

### ISSUE THREAD

**Issue by michaelsorich** [xpepermint/vue-contextable#2]
One of the validators that I will need for my project is for a field to be required (non-blank) only when a condition is met based on the value of one or more other fields in the model. Currently, it does not appear that any of the built-in validators that will handle such a scenario - none appear to use values of another field as part of the validation. I intend to look at the code more closely to try to work out how to implement this but first I would like to check that it should be relatively simple to do this with the package. Another validator of interest is to validate that the value of the field is less/greater/equal to another field (e.g. dates).

Any insight into this would be appreciated.

**Comment by xpepermint** [comment]
That should be easy to achieve just by adding a custom validator (on your model schema). Note that [contextable.js](https://github.com/xpepermint/contextablejs#schema) is using [objectschema.js](https://github.com/xpepermint/objectschemajs) and [validatable.js](https://github.com/xpepermint/validatablejs) under the hood thus you will find details there.

Here is just a hint on how your schema should look like (check the docs for details):
```js
export const schema = new Schema({
  fields: {
    name: {
      type: 'String',
      validate: [
        {
          validator: 'myCustomValidator',
          message: 'is required'
        }
      ]
    }
  },
  validatorOptions: {
     validators: {
        async myCustomValidator ({value, recipe}}) { return true } // custom validator
     }
  }
});
```

Note also that a validator's context is `Model` so you can access model's fields by using `this.{field}`. If you have nested structure, then you access parent model as `this.$parent`. Let me know if that helps.

**Comment by xpepermint** [comment]
Maybe we could add the `if` or `only` key which would run field validation only if listed validators are true. If you think this is a good idea, you can open a new issue [here](https://github.com/xpepermint/contextablejs/issues).

**Comment by xpepermint** [comment]
Feature requested here https://github.com/xpepermint/contextablejs/issues/2.

**Comment by michaelsorich** [comment]
Thanks - the example of the custom validator was sufficient for my needs although it would be simpler if there was an if key for the presence validator (not so sure about the use cases more generally).

**Comment by xpepermint** [comment]
@michaelsorich cool. The feature you requested will be added in one of the future releases.

**Comment by xpepermint** [comment]
The latest [contextable.js](https://github.com/xpepermint/contextablejs/issues/2) now provides the `condition` option.
