### ISSUE TITLE
Docs for use with server rendering

### ISSUE THREAD

**Issue by benfavre** [xpepermint/vue-contextable#5]
I have been strugling to get this to work server side.
Is this something you are working on ?

**Comment by xpepermint** [comment]
Hey @benfavre. Server-side rendering should work. 

Please tell us what would be the expected result in your case so we can maybe update the docs? Have you checked [vue-example](https://github.com/xpepermint/vue-example)?

**Comment by xpepermint** [comment]
No response from you so I'm closing this issue. Feel free to reopen it.
